### ISSUE TITLE
Network selection and protocol upgrades should be handled at runtime

### ISSUE THREAD

**Issue by q9f** [ChainSafe/forest#1402]
instead of compile-time; one binary should be able to handle all configurations.

Adding here some sub-tasks:

- [x] builtin `calibnet`/`mainnet` selection via a cli flag
- [ ] test that both networks still sync
- [ ] ~~optional include of genesis bytes for builtin network~~
- [x] support for file-based network configuration
- [x] one folder per chain db (#1418)
- [x] fix of #1498

**Comment by willeslau** [comment]
@q9f is there more info to this issue?

**Comment by q9f** [comment]
Yes, let me add some pointers.

Filecoin does have different networks for mainnet and testing and these networks have different network versions ("hard forks" or "protocol upgrades").

Currently, there is no easy way to configure a filecoin network for the forest client. Instead, we have compile-time features that enable certain chain specifications:

```
cargo build --features "interopnet"
cargo build --features "devnet"
cargo build --features "calibnet"
```

(See Makefile for examples.)

This is not optimal, it results in different binaries for different network specifications.

Now, the ultimate goal of abstraction should be:
1. one binary for all networks
2. all network configurations should be selectable by switches
3. all network versions should be selectable by switches
4. everything should function at runtime

E.g.:

```
forest --chain devnet
```

Or:

```
forest --chain calibnet --override-network-version 13
```

Or:

```
forest --chain ./path/to/custom/chain.toml
```

These are just ideas rather than expectations. I hope this clarifies what this issue is about.

**Comment by q9f** [comment]
Take a look at the calibnet pr to see how it is currently done: #1414 1370

**Comment by q9f** [comment]
This probably involves major refactoring. Related to #1396, we should be able to transition over network upgrades, sync from genesis, and eventually, allow for dynamic specification of chains. This would allow us to add support for any past and upcoming testnet by simply providing a `toml` file.

**Comment by elmattic** [comment]
Some remarks:

If env var `FOREST_CONFIG_PATH` is not set, then there's today no default location where forest is looking for the `toml` config file.

Also if a config file is present in cwd then this file should/could take precedence.

To sum-up parameters resolution could work as follows:
 - Try to load config from file:
    1. Config file is in cwd, load it.
    2. If env var `FOREST_CONFIG_PATH` is set, look for config file in this path and load it.
    3. Look in the default user path (could be something like `~/.local/share/forest/config.toml` or `~/.forest/config.toml` on linux)
    4. Load default config coded in forest binary

 - If a cli param is used, then override the one from config file (like we do today)

To select a chain/network type, cli parameter `--chain <type>` could be used to select the kind of chain to run:

```
[chain.calibnet]

bootstrap_nodes = [
  "/dns4/bootstrap-0.calibration.fildev.network/tcp/1347/p2p/12D3KooWJkikQQkxS58spo76BYzFt4fotaT5NpV2zngvrqm4u5ow",
  "/dns4/bootstrap-1.calibration.fildev.network/tcp/1347/p2p/12D3KooWLce5FDHR4EX4CrYavphA5xS3uDsX6aoowXh5tzDUxJav",
  ...
]

min_storage_pow = 2147483648

# The schedule is a list of network upgrades + genesis car file
# An upgrade could contain “hard consensus” or any “soft consensus” features (e.g. an optimization)
upgrades = [
  { name = "ohsnap",
    version = 15,
    height = 682006,
    features = ["fip_0023", "some_feature"]
  },
  { name = "chocolate",
    version = 14,
    height = 312746
  },
  ...
]

genesis.path = <location>
genesis.cid = <cid>

[chain.mainnet]
...
```

The existing parameters of today like `data_dir` could be set using the network/chain type as well.

```
[calibnet]
data_dir = "~/.forest/calibnet/db"
```

Some questions:
Should we have a dedicated `toml`/`json` config file per network/chain type rather than conflate everything in one single file?

Also we could have the network/chain configuration where genesis block is created from the same `json` like output code by command `lotus-seed`:

```
./lotus-seed genesis new localnet.json
```

See https://docs.filecoin.io/build/local-devnet/#manual-set-up.
