### ISSUE TITLE
move back to upstream version of libp2p-bitswap

### ISSUE THREAD

**Issue by q9f** [ChainSafe/forest#1421]
instead of using our pinned fork

after https://github.com/ipfs-rust/libp2p-bitswap/issues/14 is fixed

**Comment by lemmih** [comment]
Related to #1698

**Comment by LesnyRumcajs** [comment]
Let's get back to this once https://github.com/ipfs-rust/libp2p-bitswap/pull/31 is merged. Heads-up, the design changed a lot so it's definitely a non-trivial change.

**Comment by lemmih** [comment]
Hmm, they upgraded to libp2p-0.48 but the CI checks are all red. Not sure if we can switch back to `libp2p-bitswap` just yet.

**Comment by dariusc93** [comment]
> Hmm, they upgraded to libp2p-0.48 but the CI checks are all red. Not sure if we can switch back to `libp2p-bitswap` just yet.

Their CI would need to be updated since protoc is required to be installed build libp2p

**Comment by rkuhn** [comment]
Thanks to @dariusc93 libp2p-bitswap CI is green again, and I also updated the compat_test to use a currently working IPFS node and CID (this will probably require updates from time to time). I have updated to libp2p 0.49 because ipfs-embed was waiting to use an mDNS bugfix (high CPU utilization when using the Tokio runtime), so you’ll need to update to that version as well — this is going to be some effort, at least it cost me ca. two weeks to rework ipfs-embed and all its dependencies to remove NetworkBehaviourEventProcess.
