### ISSUE TITLE
Add `--detach` flag to daemonize the Forest node.

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1801]
**Issue summary**

Forest should daemonize after the various services (metrics, rpc, networking) have been setup.

**Other information and links**

https://crates.io/crates/daemonize-me
https://crates.io/crates/daemonize
https://crates.io/crates/ceviche

**Comment by elmattic** [comment]
Global anything comes with downsides.

The design choosen by `async-std` is that the executor is initialized (and can spawn threads) before entering the main function.

This is unfortunate because forking a multithreaded process is a bad idea.

Some other people using Rust+Async wanted to daemonize their process and had to move the runtime creation after forking.
Unfortunately unlike `tokio`, `async-std` doesn't let us do that.

I don't see any easy solution or workaround at the moment (and let's avoid the static initialization order fiasco).

Some interesting links:
- https://github.com/async-rs/async-std/blob/main/src/rt/mod.rs
- https://runrust.miraheze.org/wiki/Async_crate_comparison#smol
- https://docs.rs/tokio/0.2.0-alpha.6/tokio/runtime/struct.Runtime.html
- https://users.rust-lang.org/t/tokio-0-2-and-daemonize-process/42427

**Comment by lemmih** [comment]
Can we replace the `#[async_std::main]` attribute with this?
```rust
async_std::task::block_on(async {
   // our main code goes here.
}
```
