### ISSUE TITLE
FIP 29 - Beneficiary address for storage providers

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1902]
**Issue summary**

Checklist:
- [x] Are there any changes to the actor data structures that we need to be aware of?
- [x] Are there any changes to the network protocol?
- [x] Are there any changes to node behavior (eg. changes in block validation criteria, random number generation, etc)?
- [x] Are there any new magic numbers?

**Other information and links**

FIP: https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0029.md

**Comment by LesnyRumcajs** [comment]
**Beneficiary information in state**

There will be a change to `MinerInfo` struct. We have it copied from [builtin-actors](https://github.com/filecoin-project/builtin-actors/blob/b7ad2c55363c363f61275ca45ef255e28f305254/actors/miner/src/state.rs#L1212). Perhaps it will be an opportunity to import it and reduce duplication. Otherwise, we can just copy the updated version.

**Withdrawals to beneficiary**

Internal in `builtin-actors`.

**Setting the beneficiary address**

Internal in `builtin-actors`.

Related PR: https://github.com/filecoin-project/builtin-actors/pull/496

There shouldn't be any consensus change. We should be good with updating the `builtin-actors` dependency and importing or copying the `MinerInfo` struct to Forest.
