### ISSUE TITLE
Refactor forest custom libp2p metrics to use `libp2p-metrics`

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2255]
**Issue summary**

The official way of implementing Prometheus metrics for swarm event is to implement `Recorder<Event>` for `Metrics`.  We should refactor the existing forest ad-hoc Prometheus metrics into the official approach.

**Other information and links**

**Comment by tyshko5** [comment]
As for refactoring of `NetworkEvent` the current implementation which is situated in the `metrics` module of `forest_chain_sync` uses a different handling of registries and internal (meaning prometheus) location of separate metrics, and therefore refactoring would trigger some changes to prometheus and grafana handling.

**Comment by hanabi1224** [comment]
Thanks for the investigation, I guess we can merge #2311 as it is and keep this one open with a lower priority

**Comment by LesnyRumcajs** [comment]
@tyshko5 @hanabi1224 I suggest creating a separate issue with a detailed explanation of what needs to be done and putting this one into done. In general, issues should always go right (new -> in progress -> closed) so that it's easy to gather metrics on what is being worked on in the project and encourage creating more fine-grained tasks. What do you guys think?

**Comment by hanabi1224** [comment]
Sounds good!
