### ISSUE TITLE
One crate follow-up issue

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#2991]
**Issue summary**
- [x] #3037 
- [x] #3011
- [x] #3012
- [x] #3038 
- [x] #3444
- [ ] #3445
- [x] Refactor CI jobs
  - [x] #3044
- [ ] #3443
- [ ] #3013
- [x] Vendored docs

**Other information and links**

**Comment by aatifsyed** [comment]
#2957

**Comment by q9f** [comment]
> Rename forestd to forest-daemon

Curious, what's wrong with forestd?

**Comment by lemmih** [comment]
> > Rename forestd to forest-daemon
> 
> Curious, what's wrong with forestd?

I'm afraid people will mistake it for `forest` when running commands from our documentation. I can easily imagine someone accidentally running `forest --import-snapshot ...` instead of `forestd --import-snapshot`. It would be nice if `forestd` never had to be used directly, but we're not quite there yet.

**Comment by lemmih** [comment]
@aatifsyed What items are still actionable?

**Comment by aatifsyed** [comment]
All action items have their own issue
