### ISSUE TITLE
Scope GHA runs to relevant changes

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest#4721]
## Issue summary

Presently a number of checks run on EVERY pull request. These could be scoped to relevant code changes to reduce the consumption of runner minutes. 

[This example](https://github.com/ChainSafe/forest/pull/4720) removes a GHA check and does not modify any files:
<img width="1141" alt="Screenshot 2024-09-02 at 11 33 23 AM" src="https://github.com/user-attachments/assets/5fdd2a5a-3ec1-426b-a06e-892c27bc7aa1">

Some of these could be scoped to changes to any Rust code files, or in the case of documentation the relevant directory. 

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#using-filters-to-target-specific-paths-for-pull-request-or-push-events

**Comment by LesnyRumcajs** [comment]
I agree some of those can be better filtered, though I'd like to emphasize that one needs to be careful there.

Rust workflows depend on non-Rust elements - Makefiles, artefacts in the repository, even Go files, shell scripts et cetera. At one point, they even depended on markdown files (I believe someone was checking if the README files can be served by a fake server or something like this). We need to check if this is not the case anymore, otherwise a deletion of such files might trigger failure of consecutive PRs.
