### ISSUE TITLE
Test Forest with local devnet & InteropNet

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#927]
** Acceptance Criteria ** 
- A Forest node should be able to be the source for a bootstrap node for any new nodes
- A Forest node should be able to join an existing network and sync to the latest head.

Some example network topologies:
- 2 Forest Nodes with one Forest node producing blocks
- 2 Forest Nodes (one Forest block producer) and 1 Lotus node
- 2 Forest Nodes and 1 Lotus node (one Lotus block producer)

**Comment by cryptoquick** [comment]
Was this the issue @austinabell mentioned on the call?

**Comment by austinabell** [comment]
> Was this the issue @austinabell mentioned on the call?

No this is different, this was just for testing our core node implementation, the RPC stuff I mentioned is all under https://github.com/ChainSafe/forest/issues/447 epic. We've been pressed on time to scope and detail these issues, but if you do decide to look into any of them feel free to comment a question and we can provide any necessary info.

This issue is already in progress and should be closed soon once a few changes come in

**Comment by cryptoquick** [comment]
@austinabell Glad you mentioned! I was actually starting on my own solution for this. I was thinking I'd just do this in `tests/integration_tests`, like this, and just spawning and managing the processes wtihin the tests. Is this similar to what you're doing? Am I on the right track?
https://github.com/ChainSafe/forest/pull/963/files

**Comment by cryptoquick** [comment]
Wait, I'm crazy, I had no idea what I was doing there, give me a bit

**Comment by austinabell** [comment]
> @austinabell Glad you mentioned! I was actually starting on my own solution for this. I was thinking I'd just do this in `tests/integration_tests`, like this, and just spawning and managing the processes within the tests. Is this similar to what you're doing? Am I on the right track?
> https://github.com/ChainSafe/forest/pull/963/files

Actually, this issue was more around testing the node manually against the go implementation and in real use cases, since those are hard to mock in a test.

Where any tests you decide to create depends on what exactly you plan on doing, but the specific location doesn't matter that much if you are creating a new set of things.

Doing full e2e testing with p2p networking might be a little too flaky, but if you decide to go down this path I can help with any point along the way getting it setup. Ideally there would be changes to our libp2p service to allow for in memory to config to leverage the in memory networking through libp2p for more consistent testing. 

The difficulty with this specifically is that block production is generated through the [Lotus](https://github.com/filecoin-project/lotus) miner, so you won't be able to test all of the things needed with a test like this. Can you let me know what you ideally are trying to test, is there a specific functionality you had in mind?

**Comment by cryptoquick** [comment]
Okay, I sketched out more of my thinking here (same link, just with stuff that actually makes sense):
https://github.com/ChainSafe/forest/pull/963/files

I'm thinking I'll use Rust to script some tests, run some assertions, etc. I'll probably have to make these `#[async_std::test]` when I go to implement some more complex stuff. This will all be stateful, and there'd be setup and cleanup functions. I'd also manage daemon process handles, and state for each node would be defined in separate config.toml files where it makes sense.

**Comment by cryptoquick** [comment]
Also, I just got filecoin running, had to install some opencl stuff on Arch Linux. I can actually see the stdout. It's going to require some stream parsing and processing. Can do. This is gonna be a good challenge!

**Comment by cryptoquick** [comment]
I've decided to close my PR, because I don't think that approach would work well.

I was working through how one might issue commands to a pool of process handles in a certain test procedure, and then do polling-based assertions until a specific value is found for the next step of the test to proceed. Sometimes I just have to dig in and do some exploratory work to understand how something really works, but cut it short before it becomes a significant time sink. A research spike, as it were.

However, I think an approach using containers could be better. The reason is because in either case, running the binary directly could cause unpredictable results, especially with regards to lotus interop, rather than running it at a service. After building lotus:

`Caution: you have an existing lotus binary in your PATH. This may cause problems if you don't run 'sudo make install`

I was also worried that testing them within the same host network would result in a sufficient difference in network binding functionality (network device interface, ports, etc.) that there wouldn't be enough decent ways to test mDNS, AutoNat, and other libp2p complexities.

Next steps could involve seeing what other P2P projects do to solve this, and also, consider more "out of the box" solutions, such as a [NAS SBC](https://geekworm.com/collections/nas-storage/products/raspberry-pi-4-model-b-x829-dual-2-5-sata-hdd-ssd-shield-metal-case-x735-power-management-board-dc-5v-4a-power-supply-kit?variant=32947057721432) or [PicoCluster](https://www.picocluster.com/collections/pico-3/products/copy-of-pico-3-raspberry-pi4-4gb).

And finally, I'm not sure this particular GitHub issue implies a necessity for automated testing. What's likely is, at this point in time, you need tools to demonstrate and debug network architectures. More planning and thought will need into what is needed specifically. It'd be something I'd like to discuss on Monday, in addition to strategies and assessments of JSON-RPC, an HTTP API gateway, and the CLI client.

Let me know if I'm wrong or seem unclear on a few points. I certainly could be!
