### ISSUE TITLE
JSON-RPC JWT Authentication 

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#997]
**ACs**
- [ ] RPC endpoint validates jwt token from Lotus client
  - [ ] Both for HTTP & Websockets
- [ ] Test cases for both unauthorized and authorized cases

**Notes**
- How do we know who has which permissions? Is there a table? @ec2 will follow up

**Comment by cryptoquick** [comment]
@ec2 Can you take a look at the notes on this issue?

**Comment by ec2** [comment]
@cryptoquick Sorry, I forgot to power the permissions list. 
https://github.com/filecoin-project/lotus/blob/master/api/apistruct/struct.go

As you can see we dont have every RPC method implemented yet and only a subset, but everything you need to know should be there.

**Comment by cryptoquick** [comment]
Awesome, thanks! Do you have any recommendations as to how I can test this as I go?

**Comment by ec2** [comment]
First as a sanity check, when you have the JWT auth hooked up, you can try hitting some endpoints which require `write` or `admin` and see if they go through (they shouldnt work).

Then call the AuthNew RPC method to generate a new JWT Token. 
Then you can use wscat with the Authorization header set (OR you can use Lotus' CLI like how I showed you the other day by setting an ENV variable like this `FULLNODE_API_INFO=eyJmbGciOiblablab4rz5cCI6IkpXVCJ9.eyJDbGxvdyI5WvJyZtFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.pa6dg-5Q8-LT4ZiIOI_XXBRx5blablaKI420uMri2E:/ip4/192.168.0.19/tcp/9200/http`. 
The format looks like `FULLNODE_API_INFO=<JWT_TOKEN>:/ip4/<forest RPC IP>/tcp/<forest RPC PORT>/http`. 

Then as a last check, you can try replacing some of the characters so that the JWT token is wrong, and then naturally it shouldnt work.
